[platformio]
default_envs = dev

[env]
platform = espressif32@^6.5.0
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  adafruit/Adafruit AHTX0@^2.0.5
  adafruit/Adafruit Unified Sensor@^1.1.14
  adafruit/Adafruit BusIO@^1.16.1

build_flags =
  -D CORE_DEBUG_LEVEL=0
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:dev]
board = esp32-s3-devkitc-1
upload_speed = 921600

[env:release]
board = esp32-s3-devkitc-1
build_type = release
build_flags =
  ${env.build_flags}
  -Os
